networks:
  devtest:

services:
  postgres:
    image: postgres
    volumes:
      # Named volume to persist database data outside of container.
      - db_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_UESR: &user runner
      POSTGRES_PASSWORD: &password postgres
      PGUESR: *user
      PGPASSWORD: *password
      PGDATABASE: development
    ports:
      - "5434:5432"
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U runner
      interval: 3s
      timeout: 1s
      retries: 5
    networks: [devtest]

  rails:
    build:
      context: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_UESR: *user
      POSTGRES_PASSWORD: *password
      PGDATABASE: development
      PORT: 3001
    # command:
    #   - bash
    #   - -c
    #   - "bundle install && rdbg --nonstop --open --host 0.0.0.0 --port 12345 -c -- bin/rails server -b 0.0.0.0"
    ports:
      - ${PORT:-3001}:3001
      - 12345:12345
    depends_on:
      postgres: { condition: service_healthy }
    networks: [devtest]
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true

volumes:
  db_pg_data:
