networks:
  devtest:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: &user runner
      POSTGRES_PASSWORD: &password postgres
      POSTGRES_DB: &dbname development
    ports:
      - "5434:5432"
    healthcheck:
      test: pg_isready --host=127.0.0.1 --username=runner --dbname=development
      interval: 3s
      timeout: 1s
      retries: 5
    networks: [devtest]
    # commented out to allow for ephemeral setup
    # volumes:
    #   # Named volume to persist database data outside of container.
    #   - db_pg_data:/var/lib/postgresql/data

  rails:
    build:
      context: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: *user
      POSTGRES_PASSWORD: *password
      POSTGRES_DATABASE: *dbname
      PORT: 3001
#    command:
#      - bash
#      - -c
#      - "bundle install && rdbg --nonstop --open --host 0.0.0.0 --port 12345 -c -- bin/rails server -b 0.0.0.0"
    ports:
      - ${PORT:-3001}:3001
      - 12345:12345
    depends_on:
      postgres: { condition: service_healthy }
    networks: [devtest]
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true

# volumes:
#   db_pg_data:
